govau/design-system-site

- content/_shared/header-govau.md
The term SSL is confusingly deprecated. Technically SSL is now bad, and TLS good.
It's easier to just say encrypted.
Also, the certificate in most instances is not actually signed by the Australian Government.
Rather it's signed by a CA trusted by your browser.
Have changed to the same text as used by some of the cloud.gov.au pages.
(and also changed some smart-quotes to plain old apostrophes)
> Fix SSL messages

- content/components/_all.yml
**Summary**
Fixes a small typo in the [Select component description](https://gold.service.gov.au/components/select/) that referred to a  single "tem" instead of a single "item".
**Before & after:**
___
Hello from a fan of this system! ✌️ 🇦🇺 🇺🇸 Great work!
> Fixes typo in select component description

- content/components/tags/unordered.md
Noticed a small typo and grammar issue with the last paragraph. I think the intention was to say that the tags are still related, even without links on them?
> Typo & grammar fixes

- .circleci/config.yml
Hey,
This is the daily deploy script that will rebuild the DS every night at 12/1AM (depending on daylight savings).
Merge this when the color PR has been merged and you are live. Not before.
> daily rebuild

- src/js/footer/060-more.js
- src/layout/404.js
- src/layout/component/page.js
- src/layout/page.js
- src/layout/structure/header.js
- src/sass/components/_avatar.scss
- src/sass/components/_callout-with-button.scss
- src/sass/components/_component-documentation.scss
- src/sass/components/_component-status.scss
- src/sass/components/_section.scss
- src/sass/style.scss
Fix #50, #84 and #72
- Added new skip link on component pages to skip header
- Added `tabindex="0"` to skip link areas
- Added screen reader only text to contributors area
- Adjusted how spacing works on component pages ( nothing should change from this )
> Fix #50, #84 and #72

- content/components/_all.yml
- package-lock.json
- src/layout/component/navigation-accordion.js
- src/layout/component/released.js
- src/markdown/renderer.js
- src/sass/components/_badge.scss
- src/sass/components/_card--component.scss
Fixes #143 Fixes #170 Fixes #172
This PR:
- Wraps all markdown tables with `.au-table .au-table--responsive`.
- Adds highlighted statuses for components, `updated`, `new`
- Fixes a bug in the header that incorrectly made it an `<a>` instead of a `<div>`
> Highlights for components, au-table around markdown tables, header focus lock

- content/index/statisitics.md
Update number of projects to 14. 
The Civil Aviation Safety Authority's new service to allow users to apply for Aviation Reference Numbers built uses components from the design system.
> update number of projects on home page

- content/_data.yml
- content/components/page-alerts/accessibility/code.md
- content/components/page-alerts/default.md
- content/components/page-alerts/error.md
- content/components/page-alerts/examples/example-default/code.md
- content/components/page-alerts/examples/example-error/code.md
- content/components/page-alerts/examples/example-success/code.md
- content/components/page-alerts/examples/example-warning/code.md
- content/components/page-alerts/rationale/icons.md
- content/components/page-alerts/success.md
- content/components/page-alerts/warning.md
Fixes https://github.com/govau/uikit/issues/412
> Update the page-alert examples titles to their correct names

- src/layout/download/furnace.js
When you run `npm run watch` you should no longer get a warning about `checked` and `defaultChecked`
> Fix checked, defaultChecked issue in terminal

- src/layout/structure/footer.js
This pull request updates the `footer affiliate` class, to link to the [what we do](https://www.dta.gov.au/what-we-do/) page instead of the home page of [dta.gov.au](dta.gov.au)
> Update to Footer Affiliate link

- .circleci/config.yml
It doesn't really make sense to have nightly rebuilds considering every commit always gets built.
> Removed nightly rebuild from CI

- content/get-started/content.md
the link is currently pointing to `get-started/lobotomized-owl`
> fix broken link on get started page

- content/_data.yml
- content/components/_all.yml
- content/components/body/accessibility/example-code.md
- content/components/body/accessibility/example-dark.md
- content/components/body/accessibility/screenreader.md
- content/components/body/examples/example-type/example-code.md
- content/components/body/examples/example-type/example-dark.md
- content/components/body/rationale/abbreviation.md
- content/components/body/rationale/index.yml
- content/components/body/type.md
Screen reader support for `<abbr>` is [limited ](https://www.powermapper.com/tests/screen-readers/labelling/acronym-abbr-title/), so we should do our abbreviations in accordance with [readability guidelines](https://guides.service.gov.au/content-guide/terms-phrases/#acronyms).
This way the reading-experience of a screen reader more closely user matches that of a non screen reader user.
In reference to govau/design-system-components#596
> Remove `<abbr>` tag from au-body examples

- src/layout/navigation-accordion.js
Our sidebar accordion on the components page uses an anchor tag when it should use a button.
As brought up by @decrepidos
> Use button instead of anchor for accordion

- content/components/select/disabled.md
- content/components/select/valid-invalid.md
The anchor tag was using a `link` attribute when it should have been using a `href` attribute. 
Nice work @KiriHoy 
Fixes #445
> Update incorrect attribute for anchor tags in button docs

- src/layout/search.js
fixes #471 
funky...most likely due to the updates on text inputs
Thanks to @MattFredBrooks for bringing  it up! Thanks also to @pattyde for picking it up!
fixes #471
> Hotfix - search button not taking up full width

- src/js/footer/050-furnace-code.js
A bug was identified where, when the select all button was clicked and all the checkboxes were checked, these elements were not added to the NPM copy list ( ie. such as in screenshot)
> Fix bug where select was not adding components to the npm copy list

- content/components/footer/default.md
- content/components/header/code/react-usage.md
- content/components/header/default.md
- content/components/header/hero.md
- content/get-started/content.md
- Previously our starter docs didn't clarify that prior `npm` knowledge was required to install the components. This has been reworded.
- Text inputs such as postcode and mobile had `type="text"` when then should be `type="number"` and `type="tel"`, respectively
fixes #481 
fixes #496
> Update starter docs, types for text inputs

- content/components/_all.yml
Control inputs was named incorrectly in the `all.yml` file, causing console warning when building
Will fix this:
> Fix console warning when building

- content/_data.yml
- content/components/_all.yml
- src/sass/components/_navigation-accordion.scss
Added some padding to the `<li>` that wrapped the anchor.
**before:**
**after:**
> fix focus state around component sidebar links

- src/sass/components/_code.scss
Currently the copy on react code exports sits on top of the text if the exports are too long.
One solution to this was to add a padding-top to push the 'Copy' button up so it sits just above the export line. 
By implementing this solution  the code exports would look like so:
**Desktop:**
**Mobile:**
> Add padding-top to fix 'Copy' button  spacing on code exports

- src/assets/js/chameleon.js
- src/layout/customise/page.js
This is the final step, linked to: https://github.com/govau/chameleon/pull/139 so that chameleon will load the correct template instead of hard coding the `home` template the whole time.
With this PR chameleon will serve the correct template if it is in the `templates/` folder.
> Make chameleon template route dynamic

- content/templates/home/tips.md
Thanks @gordcorp 
```
cloud.gov.au will start managing this project's CF_* env vars in circleci, and to
make it easier for us we need to have a standard naming convention for environment
variables across all repos we look after.
Nothing should change for this project, this is really just house cleaning to use
the standard names.
The standard naming convention is:
CF_API_PROD
CF_API_STAGING
CF_ORG
CF_PASSWORD_PROD
CF_PASSWORD_STAGING
CF_SPACE
CF_USERNAME
After this has been merged we can remove any CF_* env vars in circleci that arent
in the above list.
```
> Use cloud.gov.au naming convention for env vars in circleci

- content/download/intro-designers-sidebar.md
- src/layout/download/intro-sidebar.js
We should link to the version controlled sketch file in the [design system sketch file](https://github.com/govau/design-system-sketch-file) repo master branch
fixes #614
> Change sketch download link to github repo

- content/components/direction-links/default.md
First reported at:
https://community.digital.gov.au/t/direction-links/77/3
> Moved back arrow to render prior to text label.

- content/components/card/card-link.md
- content/components/card/card-list.md
- content/components/card/default.md
- content/components/card/footer.md
- content/components/card/header.md
`<AUcardTitle>` is closed with a `<h3>` instead of `<\AUcardTitle>` in the react code examples for the card component
> Fix typo in card react example docs

- src/sass/components/_navigation-accordion.scss
The link colour against the background was falling slightly short of WCAG AA.
Have adjusted both values slightly
Thanks James Offer for the offering [the suggestion](https://community.digital.gov.au/t/colour-contrast-on-design-system-navigation/2304)!
> Update component page side nav link colours

- content/components/tags/default.md
There's a comma missing in the tags with links react code example.
Hope this helps! 🚀
I assumed develop was the best branch for something as small as this.
> Added missing comma in example
