govau/design-system-site

content/_data.yml, content/components/_all.yml, content/index/statisitics.md, src/layout/home/statistics.js
=> Fix #53 statistic adjustments

content/components/core/color.md, content/components/direction-links/code/react-exports.md
Fix #43 and Fix #57 
This can be seen [here](designsystem-featurebugfixes-test.apps.y.cld.gov.au)
=> Fix #43 and Fix #57

src/helper/helper.js, src/sass/base/_colors.scss, src/sass/components/_card.scss, src/sass/components/_header-govau.scss, src/sass/components/_header.scss
Fix #79, Fix #10, Adjust logging in helper, remove non generated colors
=> Fix #79, Fix #10, Adjust logging in helper, remove non generated colors

content/_data.yml, src/helper/helper.js, src/js/footer/030-mainmenu.js, src/sass/components/_mainmenu.scss
The silly `_data.yml` file wasn't being sorted every time it fetched. So in an asynchronous nature it was causing a git diff every time the site was built.
This will now only git diff when a new download happens.
=> Fix #83, #67, #90

.circleci/config.yml, src/assets/css/a11y/a11y.css, src/layout/example/a11y.js, src/sass/components/_component-status.scss
=> Fix #109, Fix #106

content/components/accordion/rationale/expand-collapse.md
Fix #117 
Update rationale to make it less confusing
=> Update accordion rationale

src/js/footer/010-helper.js, src/js/footer/040-code-copy.js, src/js/footer/050-furnace-code.js, src/layout/component/header.js, src/layout/download/furnace.js, src/sass/components/_component-header.scss
=> Google tag manager enhancements for dashboard

content/components/grid-12/code/index.yml, content/components/grid-12/code/sass-usage.md, content/components/grid-12/default.md, content/components/grid-12/examples/example-default/code.md, content/components/grid-12/examples/example-fluid/code.md, content/components/grid-12/examples/example-offset/code.md, content/components/grid-12/live/code.md, src/layout/live/page.js, src/sass/example.scss
Updating the grids page, Fix #110 Fix https://github.com/govau/uikit/issues/339 Fix #86
=> Updating the grids page, Fix #110 Fix #339 Fix #86

content/_data.yml, content/components/_all.yml, content/components/accordion/code/react-props.md, content/components/accordion/code/react-usage.md, content/components/inprogress.md, content/components/main-nav/default.md, content/components/main-nav/index.yml, content/components/search-box/default.md, content/components/search-box/index.yml, content/components/side-nav/default.md, content/components/side-nav/index.yml, content/components/skip-link/accessibility/code.md, content/components/skip-link/code/react-usage.md, content/components/skip-link/default.md, content/components/skip-link/examples/example-default/code.md, content/components/suggestions.md, src/layout/component/contributor-status.js, src/layout/component/navigation-accordion.js, src/layout/component/table-inprogress.js, src/layout/component/table-suggestions.js, src/layout/table.js, src/sass/base/_colors.scss, src/sass/components/_component-table.scss, src/sass/components/_table.scss
Fixes #135 #71 govau/uikit#389
- Add `main nav` and `side nav` to in progress
- `Skip link` documentation improved
- Add `search box` to suggestions
- Update react usage for `accordion`
- Add status to the in progress and suggested tables on the components page
=> Fixes  #135 #71 govau/uikit#389

content/components/tags/accessibility/code.md, content/components/tags/accessibility/screenreader.md, content/components/tags/default.md, content/components/tags/examples/example-default/code.md, content/components/tags/examples/example-nolink/code.md, content/components/tags/index.yml, content/components/tags/rationale/borders.md, content/components/tags/rationale/description-list.md, content/components/tags/rationale/index.yml, content/components/tags/without-links.md
Fixes https://github.com/govau/uikit/issues/367
=> Update Tags content to remove DL

googlea88b7e37223e5d10.html, src/layout/page.js
Adds verification `html` file to authenticate Google Search Console
=> add verification file for search console

src/layout/component/table-inprogress.js, src/layout/component/table-suggestions.js, src/layout/error.js, src/layout/home/features.js, src/layout/home/intro.js, src/layout/home/users.js
=> Fixes buttons with non-funcitonal href

content/components/_all.yml, src/layout/component/navigation-accordion.js, src/layout/component/released.js, src/sass/components/_badge.scss, src/sass/components/_card--component.scss
Fixes #143 
https://designsystem-featurehighlight-component-test.apps.y.cld.gov.au/components/
=> Highlight components with updated, new, or another string

src/markdown/renderer.js
=> Extended Markdown Table output

package-lock.json
fixes #172 
Latest update to @govau/header (v4.1.3) resolves this
=> Updated npm versions

content/_data.yml, content/components/side-nav/accessibility/code.md, content/components/side-nav/default.md, content/components/side-nav/examples/example-default/code.md
=> Update side navigation docs to use correct semantic html ( nav -> aside )

content/_data.yml, content/components/_all.yml, package-lock.json
Until the component is published the docs will be out of sync.
=> Sidenav version 2.0 in docs

.circleci/config.yml
=> Remove 🌲 as it takes 11 seconds ⚰️

content/_data.yml, content/components/text-inputs/block.md, content/components/text-inputs/default.md, content/components/text-inputs/textarea.md
=> Added correct html tags for text input documentation

.circleci/config.yml, content/_data.yml, content/components/text-inputs/block.md, content/components/text-inputs/default.md, content/components/text-inputs/textarea.md
=> Fixes #199

.templates/new-module/discussion/github-intro.md, content/components/accordion/discussion/github-intro.md, content/components/animate/discussion/github-intro.md, content/components/body/discussion/github-intro.md, content/components/breadcrumbs/discussion/github-intro.md, content/components/buttons/discussion/github-intro.md, content/components/callout/discussion/github-intro.md, content/components/control-input/discussion/github-intro.md, content/components/core/discussion/github-intro.md, content/components/cta-link/discussion/github-intro.md, content/components/direction-links/discussion/github-intro.md, content/components/footer/discussion/github-intro.md, content/components/grid-12/discussion/github-intro.md, content/components/header/discussion/github-intro.md, content/components/headings/discussion/github-intro.md, content/components/inpage-nav/discussion/github-intro.md, content/components/keyword-list/discussion/github-intro.md, content/components/link-list/discussion/github-intro.md, content/components/page-alerts/discussion/github-intro.md, content/components/progress-indicator/discussion/github-intro.md, content/components/responsive-media/discussion/github-intro.md, content/components/select/discussion/github-intro.md, content/components/side-nav/discussion/github-intro.md, content/components/skip-link/discussion/github-intro.md, content/components/tags/discussion/github-intro.md, content/components/text-inputs/discussion/github-intro.md
The discussion link pointed to develop instead of master.
=> Fix discussion link

content/components/body/rationale/horizontal-separator.md, content/components/body/rationale/index.yml, content/components/body/rationale/max-width.md
fixes issue https://github.com/govau/uikit/issues/406
=> hr tag aria-hidden rationale added

src/sass/base/_structure.scss
=> Add display block for print styles

content/_data.yml, package-lock.json, src/layout/structure/footer.js
=> Make footer use footerNav component

content/get-started/create-components/content.md, content/get-started/create-components/index.yml, content/get-started/customise-color/content.md, content/get-started/customise-color/index.yml, content/get-started/customise-components/index.yml, content/get-started/development-environment/index.yml
=> creating custom components init article

src/layout/404.js, src/layout/component/page.js, src/layout/example/page.js, src/layout/getstarted/page.js, src/layout/home/page.js, src/layout/page.js
This PR adds a `<meta name="description">` tags to all HTML page templates in an effort to address site SEO and PWA improvements
=> Added meta descriptions to all page templates

package.json
Bump version number to `1.0.1` in preparation for latest release.
https://github.com/govau/designsystem/pull/309
=> Bump version number 

content/components/headings/default.md, src/layout/component/page.js
Fixes https://github.com/govau/uikit/issues/550
=> Fix broken link on components/headings page

content/_data.yml, content/components/animate/rationale/nojquery.md
=> Updated animate docs

content/components/headings/default.md, src/layout/component/page.js
=> Update animate docs

content/_data.yml, content/components/_all.yml, content/components/control-input/checkbox-block.md, content/components/control-input/checkbox.md, content/components/control-input/radio-block.md, content/components/control-input/radio.md, package-lock.json
change `checked` to `defaultChecked` on react control inputs
=> Update control input docs & version

content/_data.yml, content/components/side-nav/accessibility/example-code.md, content/components/side-nav/accessibility/example-dark.md, content/components/side-nav/default.md, content/components/side-nav/examples/example-default/example-code.md, content/components/side-nav/examples/example-default/example-dark.md, content/components/side-nav/live/index.yml
=> Replace <a> with <span> in side nav active item, fixed broken tabbing on a11y example

content/components/accordion/group.md
=> Fix for wrong prop on Accordion React

content/components/footer/rationale/index.yml, content/components/footer/rationale/spacing-above.md
=> Footer spacing docs

content/components/control-input/checkbox-block.md
this will eventually all have to change once govau/design-system-components#620 is merged.
=> Fix incorrect checkbox block documentation

content/get-started/development-environment/content.md
Adds a note to append `browserlist` to the development `package.json`.
=> Added browserlist settings to development documentation

content/_data.yml, content/components/_all.yml, src/sass/components/_code-demo.scss, src/sass/components/_component-footer.scss
=> Fix cropped/unusually shaped focus states

content/_data.yml, content/components/_all.yml, content/components/control-input/accessibility/example-code.md, content/components/control-input/accessibility/example-dark.md, content/components/control-input/checkbox-block.md, content/components/control-input/checkbox.md, content/components/control-input/disabled.md, content/components/control-input/examples/example-checkbox-block/example-code.md, content/components/control-input/examples/example-checkbox-block/example-dark.md, content/components/control-input/examples/example-checkbox/example-code.md, content/components/control-input/examples/example-checkbox/example-dark.md, content/components/control-input/examples/example-disabled/example-code.md, content/components/control-input/examples/example-disabled/example-dark.md, content/components/control-input/examples/example-radio-block/example-code.md, content/components/control-input/examples/example-radio-block/example-dark.md, content/components/control-input/examples/example-radio/example-code.md, content/components/control-input/examples/example-radio/example-dark.md, content/components/control-input/examples/example-small/example-code.md, content/components/control-input/examples/example-small/example-dark.md, content/components/control-input/examples/example-valid-invalid/example-code.md, content/components/control-input/examples/example-valid-invalid/example-dark.md, content/components/control-input/radio-block.md, content/components/control-input/radio.md, content/components/control-input/small.md, content/components/control-input/valid-invalid.md, package-lock.json, src/layout/download/furnace.js, src/sass/components/_fieldset.scss
this will be merged once govau/design-system-components#620 is resolved
=> updating documentation for control inputs for version 3.0.0, bump dependencies

content/index/cards.md, src/layout/templates/page.js
As pointed out by @gordongrace we could improve some of the wording on our site.
=> Updated template / homepage wording

content/components/_all.yml
Update file type for my contributor image to `.jpg` so it doesn't appear as a broken link.
:)
=> Update image links for contributor

package-lock.json, package.json, src/layout/card.js
=> Bumped deps

package-lock.json, package.json, src/layout/card.js
- Remove default prop assignment in `card.js`
- Bump deps
- Updated `package.json` to be more _modern_
- Remove `.gitmodules`
=> Bump deps, maintainence

content/_data.yml, package-lock.json
- Bumped package-lock.json for `pancake`, `pancake-js`, `pancake-json`, `pancake-react` and `pancake-sass`
=> Bumped package-lock.json

content/_data.yml, content/components/_all.yml, content/components/core/code/scss-functions.md
Our markdown tables for the code section of the code component weren't rendering correctly. This will fix it.
=> fix markdown tables, wording for form component

content/components/header/code/react-exports.md
The react export description for the AUHeaderBrand needed updating.
=> Update AUheaderBrand description

content/support/email-the-team.md, src/layout/component/footer.js
The support email address needed to be corrected to point to @dta
=> Update support email to correct address

content/components/core/code/scss-functions.md
Some extra information and use cases have been added to the rationale for the AU-sronly class to make it clear what the intention of this class is
=> Add use case and rationale for AU-sronly class

content/components/form/examples/example-field-errors/example-field-errors.md
this workaround fixes the issue of markdown automatically.
references #517
=> workaround for markdown auto link conversion 

content/_data.yml, content/components/_all.yml, content/components/table/default.md, package-lock.json, src/layout/component/table-suggestions.js, src/layout/intro.js, src/sass/components/_tabs.scss
=> Implement keyboard accessible tabs

content/components/_all.yml
Updating the tags for the table component. 
fixing #557
=> Update tags for table component

content/_data.yml, content/components/_all.yml, content/components/table/default.md, content/components/table/examples/example-default/example-code.md, content/components/table/examples/example-striped/example-code.md, content/components/table/examples/example-width/example-code.md, content/components/table/rationale/alternating-rows.md, content/components/table/striped.md, content/components/table/width.md, package-lock.json, package.json, src/layout/component/code-demo.js, src/layout/component/table-suggestions.js, src/layout/intro.js, src/sass/components/_table.scss, src/sass/components/_tabs.scss, src/sass/example.scss
nice @KiriHoy 
fixes #557, fixes #556
=> Update table tags, add class `au-label` to text input and select labels

content/components/body/examples/example-type/example-code.md
Removed external link (no dedicated styling supported) and added `abbr` example.
=> Updated example

content/_data.yml, content/templates/content/index.yml, content/templates/content/tips.md, content/templates/form/index.yml, content/templates/form/tips.md, content/templates/home/index.yml, content/templates/home/tips.md
Adding some tips for home page, content page and forms
=> Add tips/rationale for templates

content/_data.yml, content/components/table/accessibility/example-code.md
=> Align table cell numbers right on a11y example

content/_data.yml, content/components/_all.yml, content/index/statisitics.md, package-lock.json, src/layout/home/features.js
Added links to the usage statistics cards
=> Add links to usage statistics cards

src/js/footer/070-tabs.js
Thanks @BrendanCNg for the pick up :)
```
This pull request updates the live projects from 28 to 32. New additions include:
- gg.gov.au, 
- tio.gov.au, 
- nqwia.gov.au 
- abr.gov.au
```
=> Update home page stats dev --> master

content/index/statisitics.md
=> Update live site count

content/components/card/card-list.md
=> fix typo in cardlist html snippet

content/components/_all.yml, package-lock.json
=> Typo, add missing components to templates

content/roadmap/later.md, content/roadmap/meta-data.md, content/roadmap/next.md, content/roadmap/now.md
Refer:
https://github.com/govau/design-system-site/issues/665
=> Roadmap update

content/roadmap/meta-data.md
=> Fixed parameters variable assignment for striped table on react example DEV --> MASTER

content/components/buttons/link.md
=> Updated href prop for button react component for correct `link`

content/_data.yml, content/templates/content/code/index.yml, content/templates/content/discussion/index.yml, content/templates/content/index.yml, content/templates/form/code/index.yml, content/templates/form/discussion/index.yml, content/templates/form/index.yml, content/templates/home/code/index.yml, content/templates/home/discussion/index.yml, content/templates/home/index.yml, src/layout/example/page.js, src/layout/templates/page.js
thanks @joolswood for bringing this up
=> Update page titles, templates pages

CONTRIBUTING.md
Added 'before you start' and 'initial set up' sections.
=> Expanding contributing documentation.

content/components/buttons/examples/example-default/example-code.md
Added `<button class="au-btn">Primary button</button>` to button example
=> added visual example for button default

package-lock.json, package.json
merging changes in `develop` branch to `master` identified by dependabot
=> Develop to master

content/components/_all.yml
Added Monica to contributor list for buttons and uploaded contributor image
=> added contributor image and added to buttons list
